apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jayasanka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The source repository URL and the path within that repo
  source:
    repoURL: https://Jayasanka-madhawa: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@github.com/Jayasanka-madhawa/kube_deployment.git
    targetRevision: HEAD  # You can specify a git commit, branch, or tag here
    path: dev      # The directory within the repo that contains the Kubernetes manifests

  # The destination where the application should be deployed
  destination:
    server: https://kubernetes.default.svc
    namespace: jayasanka

  # Sync Policy
  syncPolicy:
    automated:  # Uncomment if you want to enable auto sync
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Create the namespace if it does not exist

  # If needed, you can specify which Argo CD project the application belongs to
  project: default